/*================================================================================
 *  block_mcmc: stateful modular MCMC for composable Gibbs samplers
 *  Copyright (C) 2026 AI4BayesCode.
 *  Licensed under the GNU General Public License v2.0 or later
 *  (GPL-2.0-or-later). See COPYING / LICENSE at the repo root.
 *================================================================================
 *
 *  composite_block.hpp  --  a block_sampler that is itself a collection of
 *                           block_samplers, driven by a fixed Gibbs order
 *                           and backed by a shared_data_t.
 *
 *  THE RECURSIVE PROPERTY
 *  ======================
 *  composite_block is an ordinary block_sampler. Everything that holds
 *  for a leaf block holds for a composite: it has a name, a dim, a
 *  current() value, and four hot-path methods. The only thing that
 *  distinguishes it is that its step() internally runs a full Gibbs
 *  sweep over its children.
 *
 *  Because composite_block IS a block_sampler, you can nest it. A
 *  composite can be a child of another composite. This is how a
 *  hierarchical model generated by the AI agent is dropped into an
 *  outer Gibbs loop that also contains, say, a BART leaf: the outer
 *  loop just calls set_context / step / current / set_current on the
 *  composite and never needs to know how many children it has.
 *
 *  WHAT COMPOSITE_BLOCK KNOWS
 *  --------------------------
 *  Unlike leaf blocks, composite_block is allowed to know about
 *  shared_data_t. In fact, owning a shared_data_t is its whole job.
 *  The composite is the only place in block_mcmc where cross-block
 *  data flow is visible; every other piece of code (including every
 *  leaf block) sees only an opaque key-value context.
 *
 *  CURRENT() FOR A COMPOSITE
 *  -------------------------
 *  The composite's `current()` is a concatenated view of all its
 *  children's currents, in Gibbs order. This is almost never what a
 *  caller wants in the outer loop; the typical pattern is to reach
 *  into the shared_data_t via `data()` and pick out specific block
 *  values by name. `current()` exists mainly so that composite_block
 *  satisfies the block_sampler contract when nested inside a still
 *  larger composite.
 *
 *  GIBBS SWEEP ORDER
 *  -----------------
 *  Children are stored in an std::vector in the order they were added.
 *  step() iterates them in that order exactly once per call. Random
 *  scan, stochastic subset, or interleaved orders are explicit v1
 *  features; v0 is plain deterministic systematic scan because that
 *  is what every model the first release targets actually uses.
 *================================================================================*/

#ifndef AI4BAYESCODE_COMPOSITE_BLOCK_HPP
#define AI4BAYESCODE_COMPOSITE_BLOCK_HPP

#include "block_sampler.hpp"
#include "shared_data.hpp"

#include <algorithm>
#include <memory>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace AI4BayesCode {

/**
 * @brief A block_sampler composed of several child block_samplers driven
 *        by a shared_data_t.
 *
 * Typical setup:
 *     auto comp = std::make_unique<composite_block>("my_model");
 *     comp->data().set("y", y_vec);
 *     comp->data().set("X", X_flat);
 *     comp->data().set("beta", beta_init);
 *     comp->data().set("sigma", arma::vec{1.0});
 *
 *     comp->data().declare_dependencies("beta",  {"y", "X", "sigma"});
 *     comp->data().declare_dependencies("sigma", {"y", "X", "beta"});
 *     comp->data().register_refresher("residual", [](auto& d) {
 *         // derived from y, X, beta
 *     });
 *     comp->data().declare_invalidates("beta",  {"residual"});
 *     comp->data().refresh_all();
 *
 *     comp->add_child(std::make_unique<nuts_block>(...));  // beta
 *     comp->add_child(std::make_unique<nuts_block>(...));  // sigma
 *
 *     for (int s = 0; s < S; ++s) comp->step(rng);
 */
class composite_block : public block_sampler {
public:
    explicit composite_block(std::string name = "composite")
        : name_(std::move(name)) {}

    // ---- Setup (called before the first step) -------------------------

    /**
     * Take ownership of a child block. The order in which children are
     * added defines the Gibbs scan order for step(). A block_sampler
     * may be added only once.
     */
    composite_block& add_child(std::unique_ptr<block_sampler> child) {
        if (!child) {
            throw std::invalid_argument(
                "composite_block::add_child: null child");
        }
        // Seed the shared_data_t with each of the child's named outputs so
        // that dependent refreshers can be computed before the first step.
        // For a standard single-parameter block this is {name -> current()};
        // for a joint/multi-parameter block (e.g. joint_nuts_block over
        // (theta, b)) it is one entry per sub-parameter.
        auto outputs = child->current_named_outputs();
        for (const auto& kv : outputs) {
            data_.set(kv.first, kv.second);
        }
        children_.emplace_back(std::move(child));
        return *this;
    }

    /// Mutable access to the shared_data_t for setup and inspection.
    shared_data_t&       data()       noexcept { return data_; }
    const shared_data_t& data() const noexcept { return data_; }

    /**
     * Declare that `key` is intentionally contributed to history by
     * MORE THAN ONE child block. This is for the legitimate case of two
     * co-mover blocks sampling the SAME parameter inside one Gibbs scan
     * — e.g. `categorical_gibbs_block` (per-observation reallocation)
     * + `split_merge_block` (Jain-Neal 2004 split/merge) both driving
     * the cluster allocation `z`.
     *
     * Without this declaration, two children emitting the same history
     * key is treated as a composition error and get_history() throws
     * (the safety guard against accidental key collisions is kept).
     *
     * With it, get_history() keeps the series from the LAST contributing
     * child in Gibbs (add) order. Children are scanned in add order, so
     * the last contributor's series is the scan-END posterior draw of
     * the shared parameter each sweep — which is the statistically
     * correct chain. Add the owning/refining block (e.g.
     * split_merge_block) AFTER the primary block (categorical_gibbs_block)
     * so the recorded chain reflects the completed sweep.
     */
    composite_block& declare_shared_history(std::string key) {
        if (std::find(shared_history_keys_.begin(),
                       shared_history_keys_.end(), key)
            == shared_history_keys_.end()) {
            shared_history_keys_.push_back(std::move(key));
        }
        return *this;
    }

    /// Number of child blocks.
    std::size_t n_children() const noexcept { return children_.size(); }

    /// Direct access to a child block by index (useful for tests).
    block_sampler&       child(std::size_t i)       { return *children_.at(i); }
    const block_sampler& child(std::size_t i) const { return *children_.at(i); }

    // ---- block_sampler interface ---------------------------------------

    /**
     * A composite interprets `ctx` as additional shared data to merge
     * into its own shared_data_t before running the sweep. This is
     * what makes nested composites work: an outer composite feeds a
     * context down to its child composite, and the child folds that
     * context into its own shared_data_t so its grandchildren see it.
     *
     * Keys already present in this composite's shared_data_t are
     * overwritten by the incoming context.
     */
    void set_context(const block_context& ctx) override {
        for (const auto& kv : ctx) {
            data_.set(kv.first, kv.second);
        }
    }

    /**
     * One Gibbs sweep. For each child, in the order they were added:
     *   1. Build the child's context from shared_data_t dependencies.
     *   2. Push it to the child via set_context.
     *   3. child->step(rng).
     *   4. Write the child's updated value back to shared_data_t.
     *   5. Refresh any derived keys invalidated by the update.
     *
     * After the sweep, the composite's concatenated current() is
     * rebuilt lazily the next time it is requested.
     */
    void step(std::mt19937_64& rng) override {
        for (auto& child : children_) {
            const std::string& cname = child->name();

            // 1. Project shared_data into the child's context.
            block_context ctx = data_.build_context_for(cname);

            // 2. Push.
            child->set_context(ctx);

            // 3. Sample.
            child->step(rng);

            // 4. Write back EVERY named output the child exposes. For a
            //    standard MCMC block this is a single {name -> current()};
            //    for a joint block it is one entry per sub-parameter. For
            //    a VI block (engine_kind() == VI) the rng overload routes
            //    to current_sample(rng), writing a fresh q-sample (NOT
            //    the q-mean) — preserving the VI block's uncertainty for
            //    any MCMC sibling that reads it next iteration. See
            //    system_design.md §18.4 for the hybrid-correctness
            //    invariant.
            auto outputs = child->current_named_outputs(rng);
            for (const auto& kv : outputs) {
                data_.write_back(kv.first, kv.second);
            }

            // 5. Refresh derived keys invalidated by this block. The
            //    invalidation map is keyed by the BLOCK name (cname), not
            //    by individual sub-parameter names, so joint blocks
            //    declare their invalidates once under cname.
            if (!cname.empty()) {
                data_.refresh_derived_for(cname);
            }
        }
        current_dirty_ = true;
    }

    /**
     * Concatenated view of all children's current values, in Gibbs
     * order. Rebuilt on demand.
     */
    const arma::vec& current() const override {
        if (current_dirty_) {
            rebuild_current_();
            current_dirty_ = false;
        }
        return current_cache_;
    }

    /**
     * Forcibly overwrite every child's current value by splitting
     * @p theta in Gibbs order according to each child's dim(). This
     * is mainly used for checkpointing the whole composite's
     * parameter state at once; fine-grained restart should call
     * set_current on individual children.
     */
    void set_current(const arma::vec& theta) override {
        std::size_t offset = 0;
        for (auto& child : children_) {
            const std::size_t d = child->dim();
            if (offset + d > theta.n_elem) {
                throw std::invalid_argument(
                    "composite_block::set_current: theta shorter than "
                    "total child dim");
            }
            child->set_current(theta.subvec(offset, offset + d - 1));
            if (!child->name().empty()) {
                data_.write_back(child->name(), child->current());
            }
            offset += d;
        }
        if (offset != theta.n_elem) {
            throw std::invalid_argument(
                "composite_block::set_current: theta longer than total "
                "child dim");
        }
        current_dirty_ = true;
    }

    const std::string& name() const noexcept override { return name_; }

    std::size_t dim() const noexcept override {
        std::size_t total = 0;
        for (const auto& c : children_) total += c->dim();
        return total;
    }

    // ---- Kernel-tuning interface (readapt_NUTS dispatch) ---------------

    /**
     * Dispatch readapt() to every child that supports it. NUTS-family
     * children re-tune their dual-averaging state for n iterations
     * (chain state preserved bitwise). Non-NUTS children
     * (Gibbs / BART / RJMCMC / HMM / SBP / Slice / VI) have
     * supports_readapt() == false and are silently skipped.
     *
     * The composite ensures each NUTS child sees an up-to-date
     * block_context (projected from current shared_data) before
     * readapt is invoked. shared_data values are unchanged after the
     * call because each NUTS child restores its own chain state at
     * the end of its readapt().
     *
     * See system_design.md §1 (7th method) + §13 NUTS-family +
     * validator.md §24 for the full contract.
     *
     * \param n      number of internal adaptation iterations per child
     * \param reset  if true, reinitialize DA state in each NUTS child
     *               before adapting (else continue from previous state)
     * \param rng    third RNG stream (readapt_rng_ in the wrapper),
     *               separate from step()'s rng_ and predict_at's
     *               predict_rng_
     */
    void readapt_NUTS(std::size_t n,
                      bool reset,
                      std::mt19937_64& rng,
                      std::size_t max_tree_depth_override = 0) {
        if (n == 0) return;
        for (auto& child : children_) {
            if (!child->supports_readapt()) continue;
            // Project current shared_data into the child's context, so
            // the n adaptation iterations evaluate log p AT the current
            // composite state.
            block_context ctx = data_.build_context_for(child->name());
            child->set_context(ctx);
            child->readapt(n, reset, rng, max_tree_depth_override);
            // No write-back: child's state was restored at the end of
            // readapt(), so shared_data values are unchanged.
        }
    }

    /// True iff at least one child supports readapt (i.e., this
    /// composite contains any NUTS-family block). User-facing wrappers
    /// check this to decide whether to expose the 7th method
    /// `readapt_NUTS` in their RCPP_MODULE.
    bool any_child_supports_readapt() const noexcept {
        for (const auto& c : children_) {
            if (c->supports_readapt()) return true;
        }
        return false;
    }

    // ---- Predict-at (const, no state mutation) -------------------------

    /**
     * Compute predictions given replaced input values, using the current
     * MCMC state. Does NOT modify any internal state (MCMC draws,
     * adaptation counters, shared_data values). All computation happens
     * on a scratch copy.
     *
     * @param replaced_values  Keys to replace. Keys must be either:
     *   - data inputs declared via declare_data_input (e.g. "X"), or
     *   - block output names (e.g. "f_bart") when the caller has already
     *     computed predictions externally (e.g. via bart_block::predict).
     *
     * @return  A block_context containing all keys whose values changed
     *          (the replaced keys plus any derived quantities that depend
     *          on them through the refresher DAG).
     *
     * Typical usage from a user-facing class:
     *   1. For BART children: call bart_block::predict(X_new) externally.
     *   2. Inject the BART predictions as replaced_values["f_bart"].
     *   3. Call this method to propagate through refreshers.
     *   4. Collect the result.
     */
    /**
     * Compute predictions using the PREDICT DAG (generative/causal
     * direction). Two-pass algorithm:
     *
     *   Pass 1 (deterministic propagation):
     *     BFS through predict_edges_ from replaced_values. A node is
     *     recomputed iff SOME parent is in the changed set AND ALL parents
     *     are available, where "available" = {in changed set} ∪ {non-data-
     *     input key in shared_data (i.e. model parameter/derived)}. Each
     *     recomputed node is added to the changed set.
     *
     *   Pass 2 (stochastic sampling):
     *     For every key with a registered stochastic refresher whose
     *     predict-DAG parents are all available (same rule) after Pass 1,
     *     sample the node using the supplied RNG.
     *
     * Does NOT modify any internal MCMC state. All computation happens on
     * a scratch copy of shared_data_t. The `rng` is mutated by stochastic
     * sampling.
     *
     * @param replaced_values  Keys to replace. Valid keys: data_inputs
     *        declared via declare_data_input, OR block output names
     *        (for history replay / externally-computed values).
     * @param rng  RNG used for stochastic refreshers.
     * @return  block_context of nodes whose values changed (deterministic
     *          refreshes ∪ stochastic samples), excluding replaced inputs
     *          themselves.
     */
    block_context predict_at(const block_context& replaced_values,
                             std::mt19937_64& rng) const {
        // 1. Validate keys.
        const auto& valid_inputs = data_.valid_predict_inputs();
        std::unordered_set<std::string> block_names;
        for (const auto& c : children_) block_names.insert(c->name());

        for (const auto& kv : replaced_values) {
            if (!valid_inputs.count(kv.first) &&
                !block_names.count(kv.first)) {
                std::string msg =
                    "composite_block::predict_at: unknown key '"
                    + kv.first + "'. Valid data inputs: ";
                for (const auto& k : valid_inputs) msg += "'" + k + "' ";
                msg += ". Valid block outputs: ";
                for (const auto& k : block_names) msg += "'" + k + "' ";
                throw std::invalid_argument(msg);
            }
        }

        // 2. Build replaced set; deep-copy shared_data; install replaced values.
        std::unordered_set<std::string> replaced_set;
        for (const auto& kv : replaced_values) replaced_set.insert(kv.first);

        shared_data_t scratch = data_;
        std::unordered_set<std::string> changed;
        for (const auto& kv : replaced_values) {
            scratch.set(kv.first, kv.second);
            changed.insert(kv.first);
        }

        // 3. Pass 1: deterministic propagation.
        std::vector<std::string> det_refreshed =
            scratch.predict_downstream_of(changed);
        for (const auto& dk : det_refreshed) {
            if (scratch.has_refresher(dk)) {
                scratch.refresh_key(dk);
            }
            changed.insert(dk);
        }

        // 4. Pass 2: stochastic sampling (posterior predictive / y_rep).
        std::vector<std::string> stoch_sampled =
            scratch.predict_stochastic_sampleable(changed);
        for (const auto& sk : stoch_sampled) {
            scratch.run_stochastic_refresher(sk, rng);
        }

        // 5. Collect output: det_refreshed ∪ stoch_sampled, excluding
        //    replaced inputs (caller already has those).
        block_context result;
        for (const auto& dk : det_refreshed) {
            if (!replaced_set.count(dk)) result[dk] = scratch.get(dk);
        }
        for (const auto& sk : stoch_sampled) {
            if (!replaced_set.count(sk)) result[sk] = scratch.get(sk);
        }
        return result;
    }

    /**
     * Back-compat overload: predict_at with no RNG argument seeds a local
     * RNG from std::random_device{}() once per call. This is fine when
     * predict_at is invoked at most a handful of times, but for history-
     * mode (n_draws calls in a tight loop) callers should own a persistent
     * std::mt19937_64 and pass it to the rng-taking overload above — that
     * avoids repeated random_device hits (which are slow and non-
     * reproducible on macOS) and gives reproducible predictive samples
     * given a stable construction-time seed.
     */
    block_context predict_at(const block_context& replaced_values) const {
        std::mt19937_64 local_rng(std::random_device{}());
        return predict_at(replaced_values, local_rng);
    }

    /// Return the predict DAG edges for R-level introspection.
    const std::unordered_map<std::string, std::vector<std::string>>&
    get_predict_dag() const noexcept {
        return data_.predict_edges();
    }

    /**
     * Return the FULL dependency graph of the model as a named list with
     * four components:
     *
     *   $gibbs_reads       named list, block_name -> keys this block READS
     *                      from shared_data when sampling (the Gibbs
     *                      dependency DAG; populated by
     *                      declare_dependencies()).
     *   $gibbs_invalidates named list, block_name -> derived keys that
     *                      must be recomputed after this block writes
     *                      back (populated by declare_invalidates() and
     *                      served by refreshers registered via
     *                      register_refresher()).
     *   $predict_edges     named list, source_key -> downstream keys in
     *                      the GENERATIVE direction (populated by
     *                      declare_predict_edges()). This is what
     *                      predict_at walks.
     *   $data_inputs       character vector of keys declared as replaceable
     *                      prediction inputs via declare_data_input().
     *
     * Together these describe the complete parameter-structure graph.
     * R-level tools (plot_dag, etc.) render them as distinct but
     * coexisting layers.
     */
    dag_info get_dag() const {
        const auto& deps     = data_.dependencies();
        const auto& invals   = data_.invalidates();
        const auto& preds    = data_.predict_edges();
        const auto& ctxs     = data_.context_edges();
        const auto& inputs   = data_.valid_predict_inputs();

        dag_info out;
        for (const auto& kv : deps)   out.gibbs_reads[kv.first]       = kv.second;
        for (const auto& kv : invals) out.gibbs_invalidates[kv.first] = kv.second;
        for (const auto& kv : preds)  out.predict_edges[kv.first]     = kv.second;
        for (const auto& kv : ctxs)   out.context_edges[kv.first]     = kv.second;
        out.data_inputs.assign(inputs.begin(), inputs.end());
        return out;
    }

    // ---- History (delegates to children) ---------------------------------

    /**
     * Enable/disable history recording on ALL children.
     */
    void set_keep_history(bool keep) override {
        keep_history_ = keep;
        for (auto& child : children_) {
            child->set_keep_history(keep);
        }
    }

    /**
     * Enable/disable tree snapshot recording (BART-family only) on ALL
     * children. Non-BART children silently ignore.
     */
    void set_keep_tree(bool keep) override {
        keep_tree_ = keep;
        for (auto& child : children_) {
            child->set_keep_tree(keep);
        }
    }

    /**
     * Clear history on ALL children (e.g. after burnin).
     */
    void clear_history() override {
        for (auto& child : children_) {
            child->clear_history();
        }
    }

    /**
     * History size = the minimum across children (they should all agree).
     */
    std::size_t history_size() const noexcept override {
        if (children_.empty()) return 1;
        std::size_t min_sz = children_[0]->history_size();
        for (std::size_t i = 1; i < children_.size(); ++i) {
            min_sz = std::min(min_sz, children_[i]->history_size());
        }
        return min_sz;
    }

    /**
     * Composite's get_history() recursively calls each child's
     * get_history() and MERGES the per-child named lists into one flat
     * list. Every entry keeps its child's name (or whatever sub-keys
     * the child chose to expose). Nested composites therefore flatten
     * into a single list; there is no artificial nesting by composite
     * name.
     *
     * Contract: child names/sub-keys must be unique across siblings.
     * If two children produce the same key, this method throws.
     */
    history_map get_history() const override {
        history_map out;
        for (const auto& child : children_) {
            history_map cl = child->get_history();
            for (auto& kv : cl) {
                if (out.count(kv.first)) {
                    // A key contributed by >1 child is normally a
                    // composition error. The single exception is an
                    // explicitly declared shared-history key: two
                    // co-mover blocks legitimately drive the same
                    // parameter in one sweep (e.g. categorical_gibbs +
                    // split_merge on `z`). Children are scanned in add
                    // order, so the LAST contributor's series is the
                    // scan-end posterior draw — keep it, do not throw.
                    if (std::find(shared_history_keys_.begin(),
                                  shared_history_keys_.end(), kv.first)
                        != shared_history_keys_.end()) {
                        out[kv.first] = std::move(kv.second);
                        continue;
                    }
                    throw std::runtime_error(
                        "composite_block::get_history: duplicate key '"
                        + kv.first + "' contributed by multiple children "
                        "(if two blocks intentionally co-sample the same "
                        "parameter, declare it via "
                        "declare_shared_history(\"" + kv.first + "\"))");
                }
                out.emplace(kv.first, std::move(kv.second));
            }
        }
        return out;
    }

private:
    void rebuild_current_() const {
        current_cache_.set_size(dim());
        std::size_t offset = 0;
        for (const auto& child : children_) {
            const arma::vec& v = child->current();
            if (v.n_elem > 0) {
                current_cache_.subvec(offset, offset + v.n_elem - 1) = v;
            }
            offset += v.n_elem;
        }
    }

    std::string                                 name_;
    std::vector<std::unique_ptr<block_sampler>> children_;
    shared_data_t                               data_;

    // History keys intentionally contributed by >1 child (co-mover
    // blocks on the same parameter, e.g. categorical_gibbs +
    // split_merge on `z`). Empty by default => get_history() behaves
    // exactly as before (throw on any duplicate key).
    std::vector<std::string>                    shared_history_keys_;

    // Mutable cache for current(); invalidated on every step / set_current.
    mutable arma::vec current_cache_;
    mutable bool      current_dirty_ = true;
};

} // namespace AI4BayesCode

#endif // AI4BAYESCODE_COMPOSITE_BLOCK_HPP
