# ----------------------------------------------------------------------------
# run_gaussian.R
#
# End-to-end demo of GaussianLocationScale.cpp. Follow this pattern for any
# sampler generated by the AI4BayesCode skill:
#
#   1. Source AI4BayesCode's helper script to get ai4bayescode_sourceCpp().
#   2. Call ai4bayescode_sourceCpp("YourModel.cpp", AI4BayesCode_path = ...).
#   3. Construct the class, step it, read draws out with get_current().
#
# Requirements
# ------------
#   - R with Rcpp and RcppArmadillo installed.
#   - AI4BayesCode folder present on disk; this script assumes the standard
#     layout where examples/ is a sibling of R/ and include/.
# ----------------------------------------------------------------------------

# Resolve paths relative to THIS script, so it works regardless of cwd.
# Locate this script's directory portably (works under Rscript and under
# source()). Under Rscript, --file= is in commandArgs; under source(), fall
# back to getwd() (user must be cd'd into AI4BayesCode/examples/).
script_dir <- local({
    cmdargs <- commandArgs(trailingOnly = FALSE)
    farg    <- grep("^--file=", cmdargs, value = TRUE)
    if (length(farg))
        dirname(normalizePath(sub("^--file=", "", farg[1])))
    else getwd()
})
AI4BayesCode_dir <- normalizePath(file.path(script_dir, ".."))

source(file.path(AI4BayesCode_dir, "R", "AI4BayesCode_helpers.R"))

ai4bayescode_sourceCpp(
    cpp_file       = file.path(script_dir, "GaussianLocationScale.cpp"),
    AI4BayesCode_path = AI4BayesCode_dir)

# ---- Synthesize some data --------------------------------------------------
set.seed(20260410)
mu_true    <- 2.5
sigma_true <- 1.2
N          <- 200L
y          <- rnorm(N, mean = mu_true, sd = sigma_true)

cat(sprintf(
    "Generated %d points: sample mean = %.4f, sample sd = %.4f\n",
    N, mean(y), sd(y)))

# ---- Build the sampler -----------------------------------------------------
model <- new(GaussianLocationScale,
             y,           # data vector
             31337L)      # rng seed
# Initial mu / sigma are set internally to mean(y) and sd(y). To force an
# overdispersed start (e.g. for R-hat diagnostics) call
#   model$set_current(list(mu = 0, sigma = 3))
# AFTER construction.

# ---- Burn-in + keep --------------------------------------------------------
n_burnin <- 500L
n_keep   <- 2000L

model$step(n_burnin)

draws <- matrix(
    NA_real_, nrow = n_keep, ncol = 2,
    dimnames = list(NULL, c("mu", "sigma")))
for (s in seq_len(n_keep)) {
    model$step(1L)
    d <- model$get_current()
    draws[s, ] <- c(d$mu, d$sigma)
}

cat("\nPosterior summaries:\n")
cat(sprintf("  mu   : mean = %7.4f  sd = %.4f   (truth %.4f)\n",
            mean(draws[, "mu"]),    sd(draws[, "mu"]),    mu_true))
cat(sprintf("  sigma: mean = %7.4f  sd = %.4f   (truth %.4f)\n",
            mean(draws[, "sigma"]), sd(draws[, "sigma"]), sigma_true))
