"""AI4BayesCode.rhat / ess_bulk / ess_tail vs R's posterior package.

The R and Python frontends gate on the SAME thresholds (R-hat < 1.05,
ess_ratio >= 0.01), so the two implementations have to agree -- otherwise the
same draws pass on one side and fail on the other.

The reference values below were produced by `posterior` 1.6.0 on the draw sets
regenerated by `_draws()` (fixed seed, so they reproduce exactly). Regenerate
with:

    Rscript -e 'x <- as.matrix(read.csv("draws_<case>.csv", header=FALSE));
                cat(posterior::rhat(x), posterior::ess_bulk(x),
                    posterior::ess_tail(x))'

Run: python -m pytest python/tests/test_diagnostics_vs_posterior.py
"""

from __future__ import annotations

import numpy as np
import pytest

from AI4BayesCode.utils import ess_bulk, ess_tail, rhat

# case -> (rhat, ess_bulk, ess_tail) from posterior 1.6.0
REFERENCE = {
    "converged":   (1.000282, 7270.5771, 7442.3348),
    "offset":      (1.032471,   86.2643, 6009.6763),
    "scale_diff":  (1.105884, 7380.8907,   40.7197),
    "heavy_tail":  (0.999885, 7814.4894, 7802.3364),
    "cauchy":      (1.000199, 7921.6100, 8058.8375),
    "stuck_chain": (1.518458,    7.2061,   27.7685),
    "skewed":      (1.000827, 7628.1114, 7538.9449),
}


def _draws() -> dict[str, np.ndarray]:
    rng = np.random.default_rng(20260815)
    return {
        "converged":   rng.normal(size=(2000, 4)),
        "offset":      rng.normal(size=(2000, 4)) + np.array([0, 0, 0, 0.6]),
        "scale_diff":  rng.normal(size=(2000, 4)) * np.array([1, 1, 1, 2.5]),
        "heavy_tail":  rng.standard_t(2, size=(2000, 4)),
        "cauchy":      rng.standard_cauchy(size=(2000, 4)),
        "stuck_chain": np.column_stack(
            [rng.normal(size=2000) for _ in range(3)]
            + [rng.normal(size=2000) * 0.02 + 3]
        ),
        "skewed":      rng.gamma(0.5, 2.0, size=(2000, 4)),
    }


DRAWS = _draws()


@pytest.mark.parametrize("case", sorted(REFERENCE))
def test_rhat_matches_posterior(case):
    expected = REFERENCE[case][0]
    assert rhat(DRAWS[case]) == pytest.approx(expected, abs=1e-5)


@pytest.mark.parametrize("case", sorted(REFERENCE))
def test_ess_bulk_matches_posterior(case):
    expected = REFERENCE[case][1]
    assert ess_bulk(DRAWS[case]) == pytest.approx(expected, rel=1e-3)


@pytest.mark.parametrize("case", sorted(REFERENCE))
def test_ess_tail_matches_posterior(case):
    expected = REFERENCE[case][2]
    assert ess_tail(DRAWS[case]) == pytest.approx(expected, rel=1e-3)


def test_stuck_chain_is_caught_by_both_gates():
    """The regression this suite exists for: one chain parked away from the
    others must fail the R-hat gate AND collapse ESS. Before the fix, ESS was
    reported at ~8000 (full) for these draws, so ess_ratio read 3.98 and the
    'low ESS' path never fired."""
    x = DRAWS["stuck_chain"]
    n_keep = x.shape[0]
    assert rhat(x) > 1.05, "R2 gate must fail on a stuck chain"
    assert ess_bulk(x) < 100, "ESS must collapse, not report the full draw count"
    assert min(ess_bulk(x), ess_tail(x)) / n_keep < 0.005, (
        "ess_ratio must land in the escalate band"
    )


def test_rank_normalization_is_scipy_optional():
    """The numpy-only inverse-normal path must agree with the scipy one."""
    from AI4BayesCode.utils import _rank_normalize, _rank_normalize_numpy

    for case, x in DRAWS.items():
        a = _rank_normalize(x)
        b = _rank_normalize_numpy(x)
        assert np.allclose(a, b, atol=1e-7), f"{case}: scipy vs numpy path differ"
