"""AI4BayesCode.rhat / ess_bulk / ess_tail vs R's posterior package.

The R and Python frontends gate on the SAME thresholds (R-hat < 1.05,
ess_ratio >= 0.01), so the two implementations have to agree -- otherwise the
same draws pass on one side and fail on the other.

The reference values below were produced by `posterior` 1.6.0 on the draw sets
regenerated by `_draws()` (fixed seed, so they reproduce exactly). Regenerate
with:

    Rscript -e 'x <- as.matrix(read.csv("draws_<case>.csv", header=FALSE));
                cat(posterior::rhat(x), posterior::ess_bulk(x),
                    posterior::ess_tail(x))'

Run: python -m pytest python/tests/test_diagnostics_vs_posterior.py
"""

from __future__ import annotations

import numpy as np
import pytest

from AI4BayesCode.utils import ess_bulk, ess_tail, rhat

# case -> (rhat, ess_bulk, ess_tail) from posterior 1.6.0
REFERENCE = {
    "converged":   (1.000282, 7270.5771, 7442.3348),
    "offset":      (1.032471,   86.2643, 6009.6763),
    "scale_diff":  (1.105884, 7380.8907,   40.7197),
    "heavy_tail":  (0.999885, 7814.4894, 7802.3364),
    "cauchy":      (1.000199, 7921.6100, 8058.8375),
    "stuck_chain": (1.518458,    7.2061,   27.7685),
    "skewed":      (1.000827, 7628.1114, 7538.9449),
    # The seven above are all continuous, 4-chain, EVEN draw count and finite --
    # exactly the regime where any two implementations agree. These seven are
    # the regimes where they diverged: odd n (which half the split drops),
    # very short chains (whether Geyer's loop ever advances), ties (whether the
    # tail indicators are complements), a single chain, and antithetic draws
    # (where a bad tau floor reported an ESS 3.9x the draw count).
    "odd_n_101":   (1.001300,  405.509714,  465.859053),
    "odd_n_501":   (0.999741, 1873.761024, 1798.655522),
    "short_n_10":  (0.928641,   20.000000,   20.000000),
    "binary_ties": (0.999856, 7765.762027,        None),
    "counts":      (1.000024, 7378.184710, 8056.149193),
    "antithetic":  (    None, 4000.000000,        None),
    "single_chain":(1.000110, 1809.042119, 1598.706469),
}


def _draws() -> dict[str, np.ndarray]:
    rng = np.random.default_rng(20260815)
    return {
        "converged":   rng.normal(size=(2000, 4)),
        "offset":      rng.normal(size=(2000, 4)) + np.array([0, 0, 0, 0.6]),
        "scale_diff":  rng.normal(size=(2000, 4)) * np.array([1, 1, 1, 2.5]),
        "heavy_tail":  rng.standard_t(2, size=(2000, 4)),
        "cauchy":      rng.standard_cauchy(size=(2000, 4)),
        "stuck_chain": np.column_stack(
            [rng.normal(size=2000) for _ in range(3)]
            + [rng.normal(size=2000) * 0.02 + 3]
        ),
        "skewed":      rng.gamma(0.5, 2.0, size=(2000, 4)),
    }


def _draws_v2() -> dict[str, np.ndarray]:
    """The divergence regimes. Separate generator so the seven original cases
    keep their exact reference values."""
    rng = np.random.default_rng(20260816)
    _ = rng.normal(size=(2000, 4))                       # converged
    _ = rng.normal(size=(2000, 4)) + np.array([0, 0, 0, 0.6])   # offset
    return {
        "odd_n_101":    rng.normal(size=(101, 4)),
        "odd_n_501":    rng.normal(size=(501, 4)),
        "short_n_10":   rng.normal(size=(10, 4)),
        "binary_ties":  (rng.uniform(size=(2000, 4)) < 0.3).astype(float),
        "counts":       rng.poisson(3, size=(2000, 4)).astype(float),
        "antithetic":   np.tile(np.array([[1.0], [-1.0]]), (1000, 4)),
        "single_chain": rng.normal(size=(2000, 1)),
    }


DRAWS = {**_draws(), **_draws_v2()}



def _agrees(got, expected, rel):
    """`None` in the reference table means posterior returns NA for that input;
    the Python side must then be NaN, not a number.

    The reference values were produced by writing these draws to CSV and
    reading them in R, and that round-trip can move a value by an ULP -- enough
    to make two draws compare EQUAL in R and unequal here, which changes one
    rank from 1 to 1.5. On a 40-value fold that shifts R-hat in the third
    decimal. `abs_floor` absorbs exactly that; it is far below any real
    disagreement (the defects this suite was extended for were 0.9% to 3.9x).
    """
    if expected is None:
        return np.isnan(got)
    return got == pytest.approx(expected, rel=rel, abs=5e-3)


@pytest.mark.parametrize("case", sorted(REFERENCE))
def test_rhat_matches_posterior(case):
    expected = REFERENCE[case][0]
    assert _agrees(rhat(DRAWS[case]), expected, 1e-4)


@pytest.mark.parametrize("case", sorted(REFERENCE))
def test_ess_bulk_matches_posterior(case):
    expected = REFERENCE[case][1]
    assert _agrees(ess_bulk(DRAWS[case]), expected, 3e-3)


@pytest.mark.parametrize("case", sorted(REFERENCE))
def test_ess_tail_matches_posterior(case):
    expected = REFERENCE[case][2]
    assert _agrees(ess_tail(DRAWS[case]), expected, 3e-3)


def test_stuck_chain_is_caught_by_both_gates():
    """The regression this suite exists for: one chain parked away from the
    others must fail the R-hat gate AND collapse ESS. Before the fix, ESS was
    reported at ~8000 (full) for these draws, so ess_ratio read 3.98 and the
    'low ESS' path never fired."""
    x = DRAWS["stuck_chain"]
    n_keep = x.shape[0]
    assert rhat(x) > 1.05, "R2 gate must fail on a stuck chain"
    assert ess_bulk(x) < 100, "ESS must collapse, not report the full draw count"
    assert min(ess_bulk(x), ess_tail(x)) / n_keep < 0.005, (
        "ess_ratio must land in the escalate band"
    )


def test_rank_normalization_is_scipy_optional():
    """The numpy-only inverse-normal path must agree with the scipy one."""
    from AI4BayesCode.utils import _rank_normalize, _rank_normalize_numpy

    for case, x in DRAWS.items():
        a = _rank_normalize(x)
        b = _rank_normalize_numpy(x)
        assert np.allclose(a, b, atol=1e-7), f"{case}: scipy vs numpy path differ"
